export const FAQ_REVIEWED_AT = "2026-08-11";

export const FAQ_BRANDS = Object.freeze([
  { slug: "hyundai", name: "현대", officialSite: "https://www.hyundai.com/kr/ko/e" },
  { slug: "kia", name: "기아", officialSite: "https://www.kia.com/kr" },
  { slug: "genesis", name: "제네시스", officialSite: "https://www.genesis.com/kr/ko/main.html" },
  { slug: "chevrolet", name: "쉐보레", officialSite: "https://www.chevrolet.co.kr/" },
  { slug: "renault-korea", name: "르노코리아", officialSite: "https://www.renault.co.kr/" },
  { slug: "kg-mobility", name: "KG모빌리티", officialSite: "https://www.kg-mobility.com/" },
  { slug: "bmw", name: "BMW", officialSite: "https://www.bmw.co.kr/ko/index.html" },
  { slug: "mercedes-benz", name: "메르세데스-벤츠", officialSite: "https://www.mercedes-benz.co.kr/passengercars.html" },
]);

const FAQ_ITEMS = [
  {
    id: "hyundai-support-001",
    brand: "hyundai",
    category: "고객지원",
    question: "공식 FAQ에서 원하는 답을 찾지 못하면 어디로 문의하나요?",
    answer: "현대자동차 공식 FAQ 화면의 1:1 문의를 이용하거나 고객센터 안내를 확인합니다. 차량과 계정에 관한 개인정보는 이 실습 서버에 입력하지 않습니다.",
    sourceTitle: "현대자동차 자주하는 질문",
    sourceUrl: "https://www.hyundai.com/kr/ko/e/customer/center/faq",
  },
  {
    id: "hyundai-purchase-002",
    brand: "hyundai",
    category: "차량구매",
    question: "현대자동차의 일반적인 신차 구매 절차는 어떻게 확인하나요?",
    answer: "공식 구매 가이드에서 차량 검색과 견적, 구매 상담, 계약·결제, 배송·인수, 등록 순서와 단계별 안내를 확인할 수 있습니다.",
    sourceTitle: "현대자동차 구매 절차",
    sourceUrl: "https://www.hyundai.com/kr/ko/e/customer/guide/purchase",
  },
  {
    id: "hyundai-manual-003",
    brand: "hyundai",
    category: "차량관리",
    question: "차량 취급설명서와 인포테인먼트 매뉴얼은 어디서 받나요?",
    answer: "현대자동차 다운로드 센터에서 차종별 취급설명서를 찾고, 안내된 인포테인먼트 매뉴얼 경로를 이용합니다. 실제 차량의 연식과 시스템 세대를 먼저 확인하세요.",
    sourceTitle: "현대자동차 사용설명서 다운로드",
    sourceUrl: "https://www.hyundai.com/kr/ko/digital-customer-support/helpdesk/download-center",
  },
  {
    id: "kia-purchase-001",
    brand: "kia",
    category: "차량구매",
    question: "기아 차량 구입과 계약에 관한 문의는 어디에서 하나요?",
    answer: "기아 공식 FAQ는 차량 구입 관련 사항을 계약 영업점이나 공식 판매 네트워크에서 확인하도록 안내합니다.",
    sourceTitle: "기아 FAQ",
    sourceUrl: "https://www.kia.com/kr/customer-service/center/faq",
  },
  {
    id: "kia-maintenance-002",
    brand: "kia",
    category: "차량관리",
    question: "기아 차량 관리와 정비 정보는 어디에서 찾나요?",
    answer: "기아 공식 FAQ에서 연결하는 차량 관리 서비스를 이용해 정비와 차량 관리 정보를 확인합니다. 모델·연식별 조건은 공식 화면의 최신 내용을 따릅니다.",
    sourceTitle: "기아 FAQ",
    sourceUrl: "https://www.kia.com/kr/customer-service/center/faq",
  },
  {
    id: "kia-operation-003",
    brand: "kia",
    category: "차량기능",
    question: "차량 작동법이나 신기술을 영상으로 확인할 수 있나요?",
    answer: "기아 공식 FAQ는 차량 작동과 신기술 설명을 위한 공식 영상 채널을 함께 안내합니다. 내 차량에 실제 적용되는 기능인지는 차종별 설명서로 다시 확인하세요.",
    sourceTitle: "기아 FAQ",
    sourceUrl: "https://www.kia.com/kr/customer-service/center/faq",
  },
  {
    id: "genesis-share-001",
    brand: "genesis",
    category: "MY GENESIS 앱",
    question: "MY GENESIS 앱에서 차량을 다른 사용자와 공유하려면 무엇이 필요한가요?",
    answer: "주사용자가 앱의 차량 공유 관리에서 사용자를 추가합니다. 공유받을 사람도 MY GENESIS 앱을 설치하고 로그인한 상태여야 하며, 멤버십 혜택은 차량 기능 공유와 별개입니다.",
    sourceTitle: "제네시스 자주 묻는 질문",
    sourceUrl: "https://www.genesis.com/kr/ko/support/faq/faq_tab.html",
  },
  {
    id: "genesis-share-002",
    brand: "genesis",
    category: "MY GENESIS 앱",
    question: "차량 공유와 디지털 키 공유 기간은 같은가요?",
    answer: "공식 FAQ 기준으로 차량 정보·서비스 기능 공유와 디지털 키 공유의 기간 정책은 다릅니다. 디지털 키에는 별도 최대 기간이 있으므로 공유 직전 공식 앱의 최신 조건을 확인하세요.",
    sourceTitle: "제네시스 자주 묻는 질문",
    sourceUrl: "https://www.genesis.com/kr/ko/support/faq/faq_tab.html",
  },
  {
    id: "genesis-used-003",
    brand: "genesis",
    category: "중고차 등록",
    question: "중고 제네시스가 이전 사용자 계정에 등록되어 있으면 어떻게 하나요?",
    answer: "QR 등록에서 이미 다른 사용자가 등록했다는 안내가 나오면 공식 FAQ가 안내하는 다른 등록 방법을 선택해 차량번호 또는 서류 제출 절차를 진행합니다.",
    sourceTitle: "제네시스 자주 묻는 질문",
    sourceUrl: "https://www.genesis.com/kr/ko/support/faq/faq_tab.html",
  },
  {
    id: "chevrolet-service-001",
    brand: "chevrolet",
    category: "차량관리",
    question: "기존 지엠대우 차량도 쉐보레 서비스 네트워크를 이용할 수 있나요?",
    answer: "쉐보레 공식 FAQ는 기존 지엠대우 차량도 전환된 쉐보레 서비스 네트워크를 이용할 수 있다고 안내합니다. 방문 전 가까운 센터의 취급 범위를 확인하세요.",
    sourceTitle: "쉐보레 FAQ TOP 10",
    sourceUrl: "https://www.chevrolet.co.kr/faq",
  },
  {
    id: "chevrolet-navigation-002",
    brand: "chevrolet",
    category: "내비게이션",
    question: "쉐보레 내비게이션은 어떻게 업데이트하나요?",
    answer: "차량 연식과 내비게이션 종류에 따라 공식 다운로드, 별도 공급사 또는 서비스센터 방식이 달라집니다. 먼저 공식 FAQ에서 적용 차종과 시스템을 확인하세요.",
    sourceTitle: "쉐보레 내비 업데이트 FAQ",
    sourceUrl: "https://www.chevrolet.co.kr/faq/navigation",
  },
  {
    id: "chevrolet-driving-003",
    brand: "chevrolet",
    category: "운행",
    question: "자동변속기 차량이 경사로 출발 때 조금 뒤로 움직이면 모두 고장인가요?",
    answer: "경사와 차량 특성에 따라 일부 움직임이 생길 수 있지만 정도가 크거나 이상 증상이 동반되면 온라인 설명만으로 판단하지 말고 쉐보레 서비스센터에서 점검받도록 공식 FAQ가 안내합니다.",
    sourceTitle: "쉐보레 FAQ TOP 10",
    sourceUrl: "https://www.chevrolet.co.kr/faq",
  },
  {
    id: "renault-warranty-001",
    brand: "renault-korea",
    category: "보증연장",
    question: "출고 후에도 르노코리아 보증 연장 상품에 가입할 수 있나요?",
    answer: "공식 페이지는 일정 출고 기간과 주행거리 안의 대상 차량이라면 출고 후 가입이 가능하다고 안내합니다. 차종별 가능 여부와 최신 조건은 엔젤센터나 서비스 네트워크에서 확인하세요.",
    sourceTitle: "르노코리아 해피케어 보증 연장 FAQ",
    sourceUrl: "https://cdn.renault.co.kr/ko/service/care_svc_sub03.jsp",
  },
  {
    id: "renault-transfer-002",
    brand: "renault-korea",
    category: "보증연장",
    question: "차량을 매각하면 남은 보증 연장 조건은 어떻게 되나요?",
    answer: "르노코리아 공식 FAQ는 보증 연장 조건이 차량의 다음 소유자에게 승계될 수 있다고 설명합니다. 실제 매각 전에는 계약 약관과 승계 절차를 확인하세요.",
    sourceTitle: "르노코리아 해피케어 보증 연장 FAQ",
    sourceUrl: "https://cdn.renault.co.kr/ko/service/care_svc_sub03.jsp",
  },
  {
    id: "renault-repair-003",
    brand: "renault-korea",
    category: "차량관리",
    question: "보증 연장 수리는 어디에서 접수하나요?",
    answer: "가까운 르노코리아 서비스 네트워크 또는 엔젤센터에서 가입 여부와 입고 절차를 확인한 뒤 정비 접수를 진행합니다.",
    sourceTitle: "르노코리아 해피케어 보증 연장 FAQ",
    sourceUrl: "https://cdn.renault.co.kr/ko/service/care_svc_sub03.jsp",
  },
  {
    id: "kgm-payment-001",
    brand: "kg-mobility",
    category: "차량구매",
    question: "KG모빌리티 차량 대금을 여러 신용카드로 나누어 결제할 수 있나요?",
    answer: "공식 온라인 스토어 FAQ는 계약금과 인도금의 카드 사용 조건이 서로 다르다고 안내합니다. 결제 전에 영업 담당자와 최신 카드·한도 조건을 확인하세요.",
    sourceTitle: "KGM 공식 온라인 스토어 자주 묻는 질문",
    sourceUrl: "https://buy.kg-mobility.com/",
  },
  {
    id: "kgm-remote-002",
    brand: "kg-mobility",
    category: "KGM LINK",
    question: "KGM LINK의 원격 공조는 어떤 기능을 제공하나요?",
    answer: "지원 차량에서는 앱으로 원격 시동과 실내 온도, 냉난방, 유리 습기 제거 등을 제어할 수 있습니다. 전기차와 내연기관차의 작동 방식 및 지원 범위는 다를 수 있습니다.",
    sourceTitle: "KGM LINK 원격 제어",
    sourceUrl: "https://kgmlink.kg-mobility.com/service-static/service-control.do",
  },
  {
    id: "kgm-diagnostics-003",
    brand: "kg-mobility",
    category: "KGM LINK",
    question: "KGM LINK에서 차량 이상을 확인할 수 있나요?",
    answer: "공식 KGM LINK 안내는 차량 진단과 월간 리포트 등 차량 관리 기능을 제공합니다. 앱의 진단 정보는 정비사의 실제 점검을 대체하지 않습니다.",
    sourceTitle: "KGM LINK 차량 관리",
    sourceUrl: "https://kgmlink.kg-mobility.com/service-static/service-manage.do",
  },
  {
    id: "bmw-app-001",
    brand: "bmw",
    category: "My BMW 앱",
    question: "My BMW 앱의 원격 기능은 모든 차량에서 동일한가요?",
    answer: "차량 상태 확인과 여러 원격 기능을 제공하지만 국가, 모델, 장비와 소프트웨어에 따라 사용 가능 범위가 다릅니다. 차량 데이터 전송과 리모트 서비스 설정도 확인해야 합니다.",
    sourceTitle: "BMW 커뮤니케이션 센터 FAQ",
    sourceUrl: "https://www.bmw.co.kr/ko/more-bmw/customer-support.html",
  },
  {
    id: "bmw-recall-002",
    brand: "bmw",
    category: "리콜",
    question: "BMW 차량의 리콜 대상 여부는 어떻게 확인하나요?",
    answer: "공식 안내에 따라 차대번호를 준비해 자동차리콜센터에서 조회합니다. 리콜 대상 수리는 BMW 공식 서비스센터에 문의해 절차를 확인하세요.",
    sourceTitle: "BMW 커뮤니케이션 센터 FAQ",
    sourceUrl: "https://www.bmw.co.kr/ko/more-bmw/customer-support.html",
  },
  {
    id: "bmw-service-003",
    brand: "bmw",
    category: "차량관리",
    question: "BMW 서비스 인클루시브의 정비 범위는 어디서 확인하나요?",
    answer: "공식 FAQ에 엔진오일, 차량 점검, 각종 필터와 브레이크 관련 항목 등이 안내되어 있습니다. 실제 포함 여부는 계약 상품, 차량 상태와 서비스 표시 조건에 따라 확인하세요.",
    sourceTitle: "BMW 커뮤니케이션 센터 FAQ",
    sourceUrl: "https://www.bmw.co.kr/ko/more-bmw/customer-support.html",
  },
  {
    id: "mercedes-id-001",
    brand: "mercedes-benz",
    category: "디지털 서비스",
    question: "메르세데스-벤츠 디지털 서비스를 시작하려면 무엇이 필요한가요?",
    answer: "Mercedes-Benz App을 설치하고 Mercedes me ID를 등록한 뒤 이용약관 동의와 인증을 완료합니다. 차량 기능을 쓰려면 계정과 차량의 별도 연동이 필요합니다.",
    sourceTitle: "메르세데스-벤츠 디지털 서비스 FAQ",
    sourceUrl: "https://www.mercedes-benz.co.kr/passengercars/buy/digital-extras-overview.html",
  },
  {
    id: "mercedes-link-002",
    brand: "mercedes-benz",
    category: "디지털 서비스",
    question: "Mercedes me ID에 차량을 연동하려면 어떻게 하나요?",
    answer: "공식 FAQ는 차량 등록증과 신분증을 지참해 가까운 파트너사에서 본인 확인과 차량 연동을 진행하도록 안내합니다. 마스터 계정 정책도 함께 확인하세요.",
    sourceTitle: "메르세데스-벤츠 디지털 서비스 FAQ",
    sourceUrl: "https://www.mercedes-benz.co.kr/passengercars/buy/digital-extras-overview.html",
  },
  {
    id: "mercedes-users-003",
    brand: "mercedes-benz",
    category: "디지털 서비스",
    question: "가족도 같은 차량의 디지털 서비스를 이용할 수 있나요?",
    answer: "마스터 사용자가 앱의 사용자 관리에서 추가 사용자를 등록할 수 있습니다. 추가 사용자도 각자의 Mercedes me ID와 앱이 필요하며, 지원 인원과 기능은 공식 앱의 최신 정책을 확인하세요.",
    sourceTitle: "메르세데스-벤츠 디지털 서비스 FAQ",
    sourceUrl: "https://www.mercedes-benz.co.kr/passengercars/buy/digital-extras-overview.html",
  },
].map((item) => Object.freeze({ ...item, reviewedAt: FAQ_REVIEWED_AT }));

export const BRAND_FAQS = Object.freeze(FAQ_ITEMS);

export function faqBrandBySlug(slug) {
  return FAQ_BRANDS.find((brand) => brand.slug === slug) ?? null;
}

export function listBrandFaqs(brand = "") {
  return brand ? BRAND_FAQS.filter((item) => item.brand === brand) : [...BRAND_FAQS];
}
